name: nextflow-kraken2
channels:
  - conda-forge
  - bioconda
dependencies:
  - fastp=0.19.6
  - kraken2=2.0.8_beta
  - bracken=2.6.0
  - krona=2.7.1
  - pandoc=2.9.2.1
  - r-base=3.6.1
  - r-data.table=1.12.2
  - r-dplyr=0.8.0.1
  - r-tidyr=0.8.3
  - r-dt=0.4