name: nextflow-kraken2
channels:
  - conda-forge
  - bioconda
dependencies:
  - fastp
  - kraken2
  - krona
  - multiqc
  - pandoc
  - r-base
  - r-data.table
  - r-dplyr
  - r-tidyr
  - r-dt
  - r-d3heatmap